# Copyright (c) 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
# - Philippe Sauter <phsauter@iis.ee.ethz.ch>

services:
  pulp-docker:
    image: hpretl/iic-osic-tools:2025.12
    environment:
      - UID=${UID}
      - GID=${GID}
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-${UID}
    user: "${UID}:${GID}"
    volumes:
      - ./:/fosic/designs/croc
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/runtime-${UID}:/tmp/runtime-${UID}
    stdin_open: true
    tty: true
    working_dir: /fosic/designs/croc
    entrypoint: /dockerstartup/scripts/ui_startup.sh
    command: --skip bash
